name: Destroy Test

on:
  pull_request:

permissions:
  contents: write
  actions: write
  pull-requests: write

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TF_DESTROY_THRESHOLD: 2
    PLAN_FILE: plan_output.txt

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Plan Summary
        id: get_plan_summary
        env:
          PLAN_FILE: ${{ env.PLAN_FILE }}
        run: |
          plan_summary=$(cat files/$PLAN_FILE | tr '\n' ' ' | tr -d '\r')
          echo "plan_summary=$plan_summary" >> $GITHUB_ENV
      

      - name: Get Destroy Count
        id: get_destroy_count
        env:
          DESTROY_THRESHOLD: ${{ env.TF_DESTROY_THRESHOLD }}
          PLAN_SUMMARY: ${{ env.plan_summary }}
        run: |
  
          destroy_count=$(echo "$PLAN_SUMMARY" | grep -oE 'Plan: [0-9]+ to add, [0-9]+ to change, [0-9]+ to destroy.' | awk '{print $8}')
 
          echo "destroy_count=$destroy_count"

          if ! [[ "$DESTROY_THRESHOLD" =~ ^[0-9]+$ ]]; then
              echo "Invalid DESTROY_THRESHOLD value: $DESTROY_THRESHOLD"
              exit 1
          fi

          if echo "$PLAN_SUMMARY" | grep -q "No changes. Your infrastructure matches the configuration."; then
              echo "No changes. Your infrastructure matches the configuration."
              destroy_count=0
          elif
              ! [[ "$destroy_count" =~ ^[0-9]+$ ]]; then
                  echo "Invalid destroy_count value: $destroy_count"
                  exit 1
          fi

          if [ "$destroy_count" -gt "$DESTROY_THRESHOLD" ]; then
              echo "Warning: There are $destroy_count resources to be destroyed in this plan."
          elif [ "$destroy_count" -gt 0 ]; then
              echo "There are $destroy_count resources to be destroyed, which is below the threshold."
          else
              echo "No resources to be destroyed"
          fi
          echo "destroy_count=$destroy_count" >> $GITHUB_ENV


      - name: Get Confirmation
        uses: actions/github-script@v7.0.1
        env:
            DESTROY_COUNT: ${{ env }}
            DESTROY_THRESHOLD: ${{ env.TF_DESTROY_THRESHOLD }}
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
                const owner = context.repo.owner;
                const repo = context.repo.repo;
                const destroyCount = parseInt(process.env.DESTROY_COUNT, 10);
                const destroyThreshold = parseInt(process.env.DESTROY_THRESHOLD, 10);
                if (destroyCount > destroyThreshold) {
                    await github.rest.issues.createComment({
                        owner: owner,
                        repo: repo,
                        issue_number: context.payload.pull_request.number,
                        body: `@${{ github.actor }} \n
                        Terraform plan evaluation detected the number of resources to be destroyed is ${destroyCount} \n
                        Please confirm if you want to proceed with the apply operation.`
                    });
                }