name: Test


on:
  schedule:
    - cron: '*/5 * * * *'

env:
  CRON-TIME:  '*/5 * * * *'

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: ${{ github.event.schedule }} == $CRON-TIME
        run: |
          echo "It works"