name: Test


on:
  schedule:
    - cron: '09 15 * * *'

env:
  ACCOUNT_NUMBER: "1234567890"

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: init
        if: github.event.schedule == '09 15 * * *'
        run: |
          echo ${{ github.env.ACCOUNT_NUNBER}}
          echo $(date +%x_%r)
          echo ${{ github.event.schedule }}