name: Test


on:
  schedule:
    - cron: '15 10 * * *'

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: github.event.schedule == '15 10 * * *'
        run: echo "It works"
      - name: Every time
        run: echo "This step will always run"