name: Test


on:
  schedule:
    - cron: '*/5 * * * *'

env:
  CRON:  '*/5 * * * *'

jobs:

  stop-start-instances:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: ${{ github.event.schedule }} == $CRON
        run: |
          echo "It works"