name: Test


on:
  schedule:
    - cron: '50 9 * * *'

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: ${{ github.event.schedule }} == '50 9 * * *'
        run: |
          echo "It works"