name: Test


on:
  schedule:
    - cron: '00 13 * * *'

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: ${{ github.event.schedule }} == '00 13 * * *'
        run: |
          echo ${{ github.event.schedule }}
          echo $(date +%x_%r)
        