name: Test


on:
  schedule:
    - cron: '30 10 * * *'

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        run: echo "It works"
      - name: Every time
        run: echo "This step will always run"