name: Test


on:
  schedule:
    - cron: '*/5 * * * *'

env:
  CRON:  '*/5 * * * *'

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        run: |
          echo "It works"