name: Test


on:
  schedule:
    - cron: '00 11 * * *'
    - cron: '05 11 * * *'
    - cron: '10 11 * * *'
    - cron: '15 11 * * *'


jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        run: |
          echo github.event.schedule
        
      - name: Every time
        run: |
          echo "This step will always run"
          echo $(date +%x_%r)