name: Test


on:
  schedule:
    - cron: '55 13 * * *'

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: init
        run: echo $(date +%x_%r)

      - name: Test
        run: |
          echo ${{ github.event.schedule }}