name: Test


on:
  schedule:
    - cron: '35 11 * * *'
    - cron: '40 11 * * *'
    - cron: '45 11 * * *'
    - cron: '50 11 * * *'


jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        run: |
          echo ${{ github.event.schedule }}
        
      - name: Every time
        run: |
          echo "This step will always run"
          echo $(date +%x_%r)