name: Test


on:
  push:
    branches:
      - main
  schedule:
    - cron: '09 15 * * *'

env:
  THIS_NAME: "A Test"

jobs:

  job-1:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: init
        if: github.event.schedule == '09 15 * * *'
        run: |
          echo $(date +%x_%r)
          echo ${{ github.event.schedule }}

      - name: test
        run: |
          echo $THIS_NAME
          ACCOUNT_NUMBER="1234567890"
          echo ${ACCOUNT_NUMBER}
          echo "::add-mask::$ACCOUNT_NUMBER"
          echo "ACCOUNT_NUMBER=${ACCOUNT_NUMBER}" >> $GITHUB_ENV

      - name: test2
        if: env.ACCOUNT_NUMBER == '1234567890'
        run: |
         echo 'it works'

