name: Test


on:
  schedule:
    - cron: '45 13 * * *'

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: init
        run: echo $(date +%x_%r)

      - name: Test
        if: github.event.schedule == '45 13 * * *'
        run: |
          echo ${{ github.event.schedule }}