name: Test


on:
  schedule:
    - cron: "3 10 * * *"

env:
  CRON:  '3 10 * * *'

jobs:

  stop-start-instances:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        if: ${{ github.event.schedule }} == $CRON
        run: |
          echo "It works"