name: Test


on:
  push:
    branches:
      - main
  schedule:
    - cron: '09 15 * * *'

env:
  ACCOUNT_NUMBER: "1234567890"

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: init
        if: github.event.schedule == '09 15 * * *'
        run: |
          echo $(date +%x_%r)
          echo ${{ github.event.schedule }}

      - name: test
        run: |
          echo ::add-mask::$ACCOUNT_NUMBER
          echo ACCOUNT_NUMBER = $ACCOUNT_NUMBER >> $GITHUB_ENV