name: Test


on:
  schedule:
    - cron: '35 10 * * *'

jobs:

  job-2:
 
    runs-on: ubuntu-latest

    steps:
  
      - name: Test
        run: echo "It works"
      - name: Every time
        run: |
          echo "This step will always run"
          echo $(date +%x_%r)